"""add password reset fields to users

Revision ID: 019a3e56a6f9
Revises: 7802282797b1
Create Date: 2026-07-08 10:46:45.793200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '019a3e56a6f9'
down_revision: Union[str, Sequence[str], None] = '7802282797b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_password_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_password_expires')
    op.drop_column('users', 'reset_password_token')
    # ### end Alembic commands ###
