"""add address id to bookings

Revision ID: 9a50d7082896
Revises: 417d38ff1b65
Create Date: 2026-07-07 09:55:54.229856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a50d7082896'
down_revision: Union[str, Sequence[str], None] = '417d38ff1b65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('address_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'addresses', ['address_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'address_id')
    # ### end Alembic commands ###
